apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: queue-h
  name: queue-h
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: queue-h
    spec:
      containers:
      - args:
        - wait-for-it
        - HqRmCuM1H2t3@35.234.77.21:6379
        - --
        - /usr/local/bin/celery
        - worker
        - -l
        - debug
        - -Q
        - priority_high
        - -A
        - analyzer
        - -n
        - worker2@%h
        - --autoscale=10,5
        - -Ofair
        image: gcr.io/omni-stride-cloud-test/central_celery_prod:latest
        imagePullPolicy: Always
        name: queue-h
        resources: {}
      restartPolicy: Always
status: {}
