# redis:

#     host: '35.242.209.197'

#     password: 'NmMtoaZ74Yyq'

#     port: '6379'

redis:

    host: 'localhost'

    password: 'hello'

    port: '6379'


mail_config:
    server: "smtp.gmail.com"

    port: 587

    username: "dev@intelipower.co.za"

    password: "DevelopMent@22"

    default_sender: "dev@intelipower.co.za"

    use_tls: False

    use_ssl: True

    name: 'Tes Insights'